/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__main
#define __PYX_HAVE__main

#include "Python.h"
struct _CCObject;
struct _CCArray;
struct _GOArray;
struct PyEditorUI;
struct PyGameOb;

/* "main.pyx":4
 * from base cimport *
 * 
 * cdef public class PyCCObject [object _CCObject, type __CCObject]:             # <<<<<<<<<<<<<<
 *     cdef CCObject* inst
 *     cdef CCObject* ob_inst(self):
 */
struct _CCObject {
  PyObject_HEAD
  struct __pyx_vtabstruct_4main_PyCCObject *__pyx_vtab;
  CCObject *inst;
};

/* "../../pyedit_engine/cy/GDArray.pyx":4
 * from base cimport *
 * 
 * cdef public class PyCCArray(PyCCObject) [object _CCArray, type __CCArray]:             # <<<<<<<<<<<<<<
 * 
 *     cdef CCArray* arr_inst(self):
 */
struct _CCArray {
  struct _CCObject __pyx_base;
};

/* "../../pyedit_engine/cy/GDArray.pyx":47
 * 
 * 
 * cdef public class GameObjArray(PyCCArray) [object _GOArray, type __GOArray]:             # <<<<<<<<<<<<<<
 *     @thread_sync
 *     def __getattr__(self, attr):
 */
struct _GOArray {
  struct _CCArray __pyx_base;
};

/* "../../pyedit_engine/cy/EditorUI.pyx":5
 * from base cimport *
 * 
 * cdef public class Editor(PyCCObject) [object PyEditorUI, type PyEditUI]:             # <<<<<<<<<<<<<<
 * 
 *     cdef EditorUI* edit_inst(self):
 */
struct PyEditorUI {
  struct _CCObject __pyx_base;
};

/* "../../pyedit_engine/cy/GameObject.pyx":5
 * from base cimport *
 * 
 * cdef public class PyGameObject(PyCCObject) [object PyGameOb, type PyGameObj]:             # <<<<<<<<<<<<<<
 *     cdef GameObject* gameob_inst(self):
 *         return <GameObject*>self.inst
 */
struct PyGameOb {
  struct _CCObject __pyx_base;
};

#ifndef __PYX_HAVE_API__main

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) __CCObject;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) __CCArray;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) __GOArray;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyEditUI;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyGameObj;

#endif /* !__PYX_HAVE_API__main */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmain(void);
#else
PyMODINIT_FUNC PyInit_main(void);
#endif

#endif /* !__PYX_HAVE__main */
